### ISSUE TITLE
android build doesn't work with Java 9

### ISSUE THREAD

**Issue by Plamen5kov** [NativeScript/setup-scripts#1]
When android _plugin for android_ is used with _java 9_ the following error occurs:
```
Starting a Gradle Daemon, 1 busy and 3 incompatible and 1 stopped Daemons could not be reused, use --status for details

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> Failed to notify project evaluation listener.
   > javax/xml/bind/annotation/XmlSchema
```

_Off topic:_
Obviously cask on mac doesn't work with java for the same reason
`$brew cask install android-sdk --verbose --debug`
```
...
==> java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
...
```

Related issue: 
https://github.com/NativeScript/nativescript-cli/issues/3130

---

Read more info on what's [the actual problem](https://stackoverflow.com/questions/43574426/how-to-resolve-java-lang-noclassdeffounderror-javax-xml-bind-jaxbexception-in-j).

**Comment by etabakov** [comment]
The setup script is updated to install Java8, until we have fix for Java9.
