### ISSUE TITLE
Windows installer: doesn't istall HAXM  

### ISSUE THREAD

**Issue by Natalia-Hristova** [NativeScript/setup-scripts#11]
After the installation open SDK manager 
[This ](https://stackoverflow.com/questions/41092207/the-intel-x86-emulator-accelerator-haxm-installer-revision-6-0-5-is-showing-no)can be releated.

![haxm-1](https://user-images.githubusercontent.com/5803037/35162109-ea266724-fd4a-11e7-98f6-9fe6b50c81b7.png)
![haxm-2](https://user-images.githubusercontent.com/5803037/35162140-0944e87e-fd4b-11e7-9e80-3506a5ae1abb.png)

**Comment by dtopuzov** [comment]
Fixed in latest scripts.
